// Code generated by mockery v2.46.3. DO NOT EDIT.

package handlersmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	passkeysv1 "buf.build/gen/go/a-novel/proto/protocolbuffers/go/passkeys/v1"
)

// MockDeletePasskey is an autogenerated mock type for the DeletePasskey type
type MockDeletePasskey struct {
	mock.Mock
}

type MockDeletePasskey_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeletePasskey) EXPECT() *MockDeletePasskey_Expecter {
	return &MockDeletePasskey_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: _a0, _a1
func (_m *MockDeletePasskey) Exec(_a0 context.Context, _a1 *passkeysv1.DeleteServiceExecRequest) (*passkeysv1.DeleteServiceExecResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *passkeysv1.DeleteServiceExecResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *passkeysv1.DeleteServiceExecRequest) (*passkeysv1.DeleteServiceExecResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *passkeysv1.DeleteServiceExecRequest) *passkeysv1.DeleteServiceExecResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*passkeysv1.DeleteServiceExecResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *passkeysv1.DeleteServiceExecRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeletePasskey_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockDeletePasskey_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *passkeysv1.DeleteServiceExecRequest
func (_e *MockDeletePasskey_Expecter) Exec(_a0 interface{}, _a1 interface{}) *MockDeletePasskey_Exec_Call {
	return &MockDeletePasskey_Exec_Call{Call: _e.mock.On("Exec", _a0, _a1)}
}

func (_c *MockDeletePasskey_Exec_Call) Run(run func(_a0 context.Context, _a1 *passkeysv1.DeleteServiceExecRequest)) *MockDeletePasskey_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*passkeysv1.DeleteServiceExecRequest))
	})
	return _c
}

func (_c *MockDeletePasskey_Exec_Call) Return(_a0 *passkeysv1.DeleteServiceExecResponse, _a1 error) *MockDeletePasskey_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeletePasskey_Exec_Call) RunAndReturn(run func(context.Context, *passkeysv1.DeleteServiceExecRequest) (*passkeysv1.DeleteServiceExecResponse, error)) *MockDeletePasskey_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeletePasskey creates a new instance of MockDeletePasskey. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeletePasskey(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeletePasskey {
	mock := &MockDeletePasskey{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
