// Code generated by mockery v2.46.3. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	services "github.com/a-novel/uservice-passkeys/pkg/services"
	mock "github.com/stretchr/testify/mock"
)

// MockUpdatePasskey is an autogenerated mock type for the UpdatePasskey type
type MockUpdatePasskey struct {
	mock.Mock
}

type MockUpdatePasskey_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdatePasskey) EXPECT() *MockUpdatePasskey_Expecter {
	return &MockUpdatePasskey_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, data
func (_m *MockUpdatePasskey) Exec(ctx context.Context, data *services.UpdatePasskeyRequest) (*services.UpdatePasskeyResponse, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *services.UpdatePasskeyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *services.UpdatePasskeyRequest) (*services.UpdatePasskeyResponse, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *services.UpdatePasskeyRequest) *services.UpdatePasskeyResponse); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.UpdatePasskeyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *services.UpdatePasskeyRequest) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdatePasskey_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockUpdatePasskey_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - data *services.UpdatePasskeyRequest
func (_e *MockUpdatePasskey_Expecter) Exec(ctx interface{}, data interface{}) *MockUpdatePasskey_Exec_Call {
	return &MockUpdatePasskey_Exec_Call{Call: _e.mock.On("Exec", ctx, data)}
}

func (_c *MockUpdatePasskey_Exec_Call) Run(run func(ctx context.Context, data *services.UpdatePasskeyRequest)) *MockUpdatePasskey_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*services.UpdatePasskeyRequest))
	})
	return _c
}

func (_c *MockUpdatePasskey_Exec_Call) Return(_a0 *services.UpdatePasskeyResponse, _a1 error) *MockUpdatePasskey_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdatePasskey_Exec_Call) RunAndReturn(run func(context.Context, *services.UpdatePasskeyRequest) (*services.UpdatePasskeyResponse, error)) *MockUpdatePasskey_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdatePasskey creates a new instance of MockUpdatePasskey. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdatePasskey(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdatePasskey {
	mock := &MockUpdatePasskey{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
